### ISSUE TITLE
Feature: I would like to make howering effect of game card as translucent. currently while, hovering it seems to be blue which hides the game image 

### ISSUE THREAD

**Issue by ankit1576** [GameSphere-MultiPlayer/GameSphere3.0#22]
## About Feature
want to add translucent effect to hover effect
## Description
want to add taranslucent effect while hovering to game card as of now it seems to be blue which hides the whole game background see screenshot of ref..
## Screenshot
![image](https://github.com/GameSphere-MultiPlayer/GameSphere3.0/assets/71921877/289bff4b-0e39-4531-af9b-582568079d23)

## Connect Us On Social Media -
- [x]  Star the repositry
- [x]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [x]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [x]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by Durgesh4993** [comment]
### Don't Forget to connect with Us:
LinkedIn: https://www.linkedin.com/company/gamesphere-multiplayer/?viewAsMember=true
GitHub: https://github.com/GameSphere-MultiPlayer
